const inicioUrl = "/central-imoveis/assets/imoveis/";

const imoveis = [
  {
    id: 1,
    titulo: "Algum titulo",
    contrato: "Aluguel",
    destaque: true,
    descricao: "Descrição mais curta",
    preco: 1234,
    localizacao: "Localização do Imóvel",
    quartos: 3,
    banheiros: 2,
    area: 200,
    estacionamento: 2,
    imagem: `${inicioUrl}property-1.jpg`,
    fullDescricao:
      "Uma descrição mais precisa do imóvel, algo para o cliente ler e prestar atenção",
    comodidades: [
      "Piscina",
      "Academia",
      "Salão de Festas",
      "Portaria 24h",
      "Área Gourmet",
      "Playground",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 2,
    titulo: "Algum titulo",
    contrato: "Aluguel",
    destaque: false,
    descricao: "Descrição mais curta",
    preco: 2345,
    localizacao: "Localização do Imóvel",
    quartos: 3,
    banheiros: 2,
    area: 200,
    estacionamento: 2,
    imagem: `${inicioUrl}property-2.jpg`,
    fullDescricao:
      "Uma descrição mais precisa do imóvel, algo para o cliente ler e prestar atenção",
    comodidades: [
      "Piscina",
      "Academia",
      "Salão de Festas",
      "Portaria 24h",
      "Área Gourmet",
      "Playground",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 3,
    titulo: "Algum titulo",
    contrato: "Aluguel",
    destaque: true,
    descricao: "Descrição mais curta",
    preco: 3456,
    localizacao: "Localização do Imóvel",
    quartos: 3,
    banheiros: 2,
    area: 200,
    estacionamento: 3,
    imagem: `${inicioUrl}property-3.jpg`,
    fullDescricao:
      "Uma descrição mais precisa do imóvel, algo para o cliente ler e prestar atenção",
    comodidades: [
      "Piscina",
      "Academia",
      "Salão de Festas",
      "Portaria 24h",
      "Área Gourmet",
      "Playground",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 4,
    titulo: "Algum titulo",
    contrato: "Compra",
    destaque: false,
    descricao: "Descrição mais curta",
    preco: 4567,
    localizacao: "Localização do Imóvel",
    quartos: 3,
    banheiros: 2,
    area: 200,
    estacionamento: 2,
    imagem: `${inicioUrl}property-1.jpg`,
    fullDescricao:
      "Uma descrição mais precisa do imóvel, algo para o cliente ler e prestar atenção",
    comodidades: [
      "Piscina",
      "Academia",
      "Salão de Festas",
      "Portaria 24h",
      "Área Gourmet",
      "Playground",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 5,
    titulo: "Algum titulo",
    contrato: "Compra",
    destaque: true,
    descricao: "Descrição mais curta",
    preco: 5678,
    localizacao: "Localização do Imóvel",
    quartos: 3,
    banheiros: 2,
    area: 200,
    estacionamento: 2,
    imagem: `${inicioUrl}property-2.jpg`,
    fullDescricao:
      "Uma descrição mais precisa do imóvel, algo para o cliente ler e prestar atenção",
    comodidades: [
      "Piscina",
      "Academia",
      "Salão de Festas",
      "Portaria 24h",
      "Área Gourmet",
      "Playground",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 6,
    titulo: "Algum titulo",
    contrato: "Compra",
    destaque: false,
    descricao: "Descrição mais curta",
    preco: 6789,
    localizacao: "Localização do Imóvel",
    quartos: 3,
    banheiros: 2,
    area: 200,
    estacionamento: 2,
    imagem: `${inicioUrl}property-3.jpg`,
    fullDescricao:
      "Uma descrição mais precisa do imóvel, algo para o cliente ler e prestar atenção",
    comodidades: [
      "Piscina",
      "Academia",
      "Salão de Festas",
      "Portaria 24h",
      "Área Gourmet",
      "Playground",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
];

export default imoveis;
