const inicioUrl = "/central-imoveis/assets/imoveis/";

const imoveis = [
  {
    id: 1,
    titulo: "Casa",
    contrato: "Aluguel",
    destaque: true,
    maisProcurado: false,
    quartos: 3,
    estacionamento: 2,
    dataCadastro: "2024-09-01",
    descricao: "Casa espaçosa com jardim e piscina, perfeita para a família.",
    preco: 1234,
    localizacao: "Bairro Jardim Primavera",
    cidade: "São José do Rio Pardo",
    banheiros: 2,
    area: 200,
    imagem: `${inicioUrl}property-1.jpg`,
    fullDescricao:
      "Casa de 3 quartos com ampla área de lazer, jardim, piscina e churrasqueira. Condomínio com segurança 24h e fácil acesso a comércios.",
    comodidades: [
      "Piscina",
      "Academia",
      "Churrasqueira",
      "Portaria 24h",
      "Área Gourmet",
      "Jardim Privativo",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 2,
    titulo: "Apartamento",
    contrato: "Aluguel",
    destaque: false,
    maisProcurado: true,
    quartos: 2,
    estacionamento: 1,
    dataCadastro: "2024-08-25",
    descricao: "Apartamento moderno no centro da cidade, com vista incrível.",
    preco: 2345,
    localizacao: "Bairro Nova Esperança",
    cidade: "Mococa",
    banheiros: 2,
    area: 90,
    imagem: `${inicioUrl}property-2.jpg`,
    fullDescricao:
      "Apartamento moderno e elegante no coração da cidade. Vista panorâmica, sala em conceito aberto e condomínio com academia e salão de festas.",
    comodidades: [
      "Terraço Panorâmico",
      "Academia",
      "Salão de Festas",
      "Portaria 24h",
      "Elevador",
      "Área de Trabalho Compartilhada",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 3,
    titulo: "Studio",
    contrato: "Aluguel",
    destaque: true,
    maisProcurado: false,
    quartos: 1,
    estacionamento: 0,
    dataCadastro: "2024-09-10",
    descricao: "Studio aconchegante para quem busca praticidade e conforto.",
    preco: 3456,
    localizacao: "Bairro Residencial das Flores",
    cidade: "Tapiratiba",
    banheiros: 1,
    area: 45,
    imagem: `${inicioUrl}property-3.jpg`,
    fullDescricao:
      "Charmoso studio otimizado para praticidade. Localizado em bairro vibrante com fácil acesso a bares, restaurantes e transporte público.",
    comodidades: [
      "Lavanderia Compartilhada",
      "Área Gourmet",
      "Piscina",
      "Academia",
      "Portaria 24h",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 4,
    titulo: "Casa",
    contrato: "Compra",
    destaque: false,
    maisProcurado: true,
    quartos: 4,
    estacionamento: 2,
    dataCadastro: "2024-09-05",
    descricao:
      "Residência de alto padrão com 4 suítes e área de lazer completa.",
    preco: 4567,
    localizacao: "Bairro Alto da Colina",
    cidade: "Itobi",
    banheiros: 5,
    area: 500,
    imagem: `${inicioUrl}property-1.jpg`,
    fullDescricao:
      "Residência de alto padrão com 4 suítes e acabamentos de primeira linha. Conta com piscina aquecida, quadra de tênis e paisagismo impecável.",
    comodidades: [
      "Piscina Aquecida",
      "Quadra de Tênis",
      "Lareira",
      "Sauna",
      "Jardim de Inverno",
      "Home Theater",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 5,
    titulo: "Apartamento",
    contrato: "Compra",
    destaque: true,
    maisProcurado: false,
    quartos: 2,
    estacionamento: 1,
    dataCadastro: "2024-08-15",
    descricao: "Apartamento aconchegante em bairro tranquilo, perto de tudo.",
    preco: 5678,
    localizacao: "Bairro Recanto Feliz",
    cidade: "Vargem Grande do Sul",
    banheiros: 2,
    area: 85,
    imagem: `${inicioUrl}property-2.jpg`,
    fullDescricao:
      "Apartamento de 2 quartos em bairro tranquilo. Ideal para casais ou famílias pequenas, com piscina, playground e academia no prédio.",
    comodidades: [
      "Piscina",
      "Academia",
      "Salão de Festas",
      "Playground",
      "Portaria 24h",
      "Mini Mercado Interno",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
  {
    id: 6,
    titulo: "Terreno",
    contrato: "Compra",
    destaque: false,
    maisProcurado: false,
    quartos: null,
    estacionamento: 0,
    dataCadastro: "2024-09-08",
    descricao: "Amplo terreno para construção no condomínio de luxo.",
    preco: 6789,
    localizacao: "Bairro dos Pássaros",
    cidade: "Caconde",
    banheiros: null,
    area: 1200,
    imagem: `${inicioUrl}property-3.jpg`,
    fullDescricao:
      "Amplo terreno de 1200 m² para construir a casa dos sonhos em um condomínio com segurança 24h, lagos e trilhas para caminhada.",
    comodidades: [
      "Lagos",
      "Trilhas para Caminhada",
      "Segurança 24h",
      "Club House",
      "Quadras Poliesportivas",
    ],
    maisImagens: [
      `${inicioUrl}property-1.jpg`,
      `${inicioUrl}property-2.jpg`,
      `${inicioUrl}property-3.jpg`,
    ],
  },
];

export default imoveis;
